export { default as AboutPage } from "./about/About.astro"
export { default as CommunityPage } from "./community/Comunity.astro"
export { default as ContactPage } from "./contact/Contact.astro"
export { default as HomePage } from "./home/Home.astro"
export { default as LegalPage } from "./legal/Legal.astro"
export { default as ProductPage } from "./product/Product.astro"
export { default as DeliveryPage } from "./empaques/Delivery.astro"
export { default as HealingKitPage } from "./kit-sanacion/KitSanacion.astro"
export { default as HowToBuyPage } from "./how-to-buy/HowToBuy.astro"
export { default as EnviosPage} from "./envios/Envios.astro"